[build]
  command = "npm run build"
  publish = "dist"  # Changed from "build" to "dist"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"  # Added this plugin

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[context.production]
  command = "npm run build"

[context.production.environment]
  VITE_APP_ENV = "production"

# Increase build memory limit
[build.processing]
  skip_processing = false